external_components:
  - name: heltec_lora        # the same folder name
    version: "1.0.0"
    platforms: [esp32]
    requirements:
      - Heltec_ESP32
    files:
      - heltec_lora.h
      - heltec_lora.cpp
